### ISSUE TITLE
Checkbox 'General subscribe' is NOT selected if user selected it when creating an account

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1588]
**Description**:
Checkbox 'General subscribe' is NOT selected if user selected it when creating an account

**Expected behavior**:
Checkbox is selected

**To Reproduce**:
1. Open website
2. Tap 'Create an Account'
3. Fill the form (Name, surname, email, password, confirm password)
4. Select 'Subscribe to newsletter' Checkbox
5. Tap 'Sign in'
6. Log in
7. Open My Account -> Open Newsletter page

**Actual result**:
Checkbox 'General subscribe' is NOT selected
It is NOT selected in Admin panel too

**Notes**:
User selects checkbox -> taps Save ->Success message -> Refreshes page => Checkbox is NOT selected

**Comment by zurabi-sardarov** [comment]
This issue is already fixed according to master branch. Should be just released.

**Comment by lianastaskevica** [comment]
Hello @zurabi-sardarov! I can still reproduce the issue on the latest master. Where do you see it being fixed?

**Comment by zurabi-sardarov** [comment]
@lianastaskevica  https://youtu.be/RiAx45JJanw

**Comment by carinadues** [comment]
Hey! I tested now on [master](https://master.d25kd40decjpue.amplifyapp.com/default/) and it worked. It was necessary to open MailDev and click on the subscription confirmation link that was sent. After doing that, the checkbox is checked in My account.

**Comment by aleksandrakorolova** [comment]
Closing task because can't reproduce:
1. Works good If setting Need to confirm set to no
2. Need to confirm subscription via subscription confirmation link if Need to confirm set to yes

Created a separate task for the wrong notification message #2610
